name: Mirror to Public Repo

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # don't inject GITHUB_TOKEN

      - run: |
          git remote add public "https://x-access-token:${{ secrets.PUBLIC_REPO_PAT }}@github.com/Chinthan-Rk/simple-burp-bambdas.git"
          git push public refs/heads/main:refs/heads/main --force
